### ISSUE TITLE
Invoke-FalconRtr doesn't return 'get' results in v2.1.3

### ISSUE THREAD

**Issue by bk-cs** [CrowdStrike/psfalcon#79]
An error is produced referencing a null value when adding the `batch_get_cmd_req_id` property. This was because `Invoke-FalconRtr` was not checking the right place in an `Invoke-FalconBatchGet` command response (which is what `Invoke-FalconRtr` uses when you use the `get` command).

**Comment by bk-cs** [comment]
Issue has been fixed for v2.1.4 and the corresponding `psfalcon.ps1` and `real-time-response.ps1` public function files have been updated.

You can fix it yourself by replacing `Public\psfalcon.ps1` and `Public\real-time-response.ps1` in your PSFalcon module folder with the corresponding files that have been updated for the future release:

https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Public/psfalcon.ps1
https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Public/real-time-response.ps1

**Comment by zgold15** [comment]
The issue is coming from the \Private\private.ps1 file. I updated the two files above and still receive the same error. Coming from line 582 char:35. The line of code I am getting as an error is:

$Result = Write-Result $Request

**Comment by bk-cs** [comment]
Did you restart your PowerShell session or reload the module after applying those files? Copying the files in won't make changes until the module is reloaded.

I've made no changes to the `Private\Private.psd1` file on my own device (only to the referenced `Public` files) and the `get` command works as expected. Can you provide a screenshot of the error you're receiving in case it's different than the one I had?

**Comment by zgold15** [comment]
Write-Result : 40401: Could not establish sensor comms

+                         $Result = Write-Result $Request
+                                   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Threadin...esponseMessage]:Task`1) [Write-Result], Exception
    + FullyQualifiedErrorId : 570b7214-6c3e-4f5f-a71e-988d3efff766,Write-Result

**Comment by bk-cs** [comment]
`40401: Could not establish sensor comms` is a Real-time Response API error. It's produced when the device you're attempting to connect to is not online. This is likely unrelated to this GitHub issue.

The error that I was referring to was that `batch_get_cmd_req_id` did not exist when it was attempting to output results for `Invoke-FalconRtr -Command get`, but the session was starting as expected (i.e. no `40401` error).

**Comment by zgold15** [comment]
Okay yes it is working now I see the issue. Thank you for the help/description.

**Comment by datorr2** [comment]
Seems like this still isn't working in v2.1.4.

```powershell
Get-Module 'PSFalcon'

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.4                 PSFalcon                            {Add-FalconCidGroupMember, Add-FalconGroupRole, Add-FalconHostTag, Add-FalconRole…}

$response = Invoke-FalconRTR -HostIds $online -Command ps

$response | Select-Object -ExcludeProperty aid | Format-Table

batch_id                             session_id                           cloud_request_id                     complete offline_queued errors                                  stderr stdout
--------                             ----------                           ----------------                     -------- -------------- ------                                  ------ ------
b40e4eb8-b98d-40d8-9176-8560146f907f a74f75d1-b07b-4784-8aeb-772ee4cc46ab 01147018-d5bd-41a2-af91-73832af0e94b     True          False                                                C:\
                                                                                                                  False          False 40401: Could not establish sensor comms
b40e4eb8-b98d-40d8-9176-8560146f907f c61c290d-5aee-4c28-ba97-582dcdd82ed2 204de5c6-2395-48d2-9cd9-0e0c7fb492a9     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 6934be91-f86f-441c-976c-15308a3694f8 5ac5b80e-4be6-4a73-9068-51f1ad04c1f4     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 059c8bdf-9f7e-4f06-a247-1c5f9c3c25ff 078d3f8b-211c-47be-87e4-22ce4da4cf4a     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 780c9714-fb2f-49b7-b856-eb14b3c45ceb da6ecba4-c591-4cf5-bff1-24195bdde247     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 2b04f9ff-a62c-4175-ada4-65117e53d7cd d34a0025-7d5f-40a9-b275-4c55b2ba4d40     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f c4cce02d-5f89-4c87-a99c-553cb1cdc746 4f30e852-7c36-45b5-8abf-f3aea25abb09     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 974146f7-44c8-4898-8310-8bc145e4ea3a 62194a9d-de1e-4db7-8f36-346468d497c3     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 67ab4ac6-f815-4d79-959e-4aa293368fe4 022df32b-cd91-4f24-9aa2-420e71ce3248     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f d63f4c56-7b54-4392-b19c-2e4a50b82cd8 03132da7-4aa9-4dcc-b617-199cf59fdb19     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f f9cd1371-eaae-4686-81a9-1f4496c53009 ef822465-1b24-4ce2-aeb0-1cbe40978c94     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 2f67814a-453c-4f87-921a-f94d8ceae5ab f475fcc0-6ff5-48bd-bcfc-f9ab622ba25e     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 055eacd2-8426-4e03-a057-a2c575d20163 0619bc93-2df3-4a82-8e51-55556bb7c599     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f ff5e39b7-509a-4d4d-ac41-62bfbd8008d2 61a48a01-cfa2-4adc-86c4-4a5781f89547     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 4cc22a0a-4e70-47ab-819c-0a7b226745c8 822562eb-3a1b-4314-944d-fb5a4e914e47     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f a7baf05b-28a1-4f2b-8991-d043038d0e14 379b119b-686c-4354-b1ca-4bb244cbd102     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 1a3e8ae3-b35a-4ba1-84ca-4a79ec96e710 edee0afa-6829-46a2-94c8-8c4d84493953     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 4b018c40-2a3e-474f-8485-7e164d53d1c6 aa4d23b8-96ba-4efa-b115-edcfd2951097     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 580a4506-0a7a-4335-981b-4b7ffa7fa50d 058bde92-c8ba-4308-9bb7-7b34cb353cbd     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f a0e18211-49e9-4cef-a61b-24deaed9b3bb d0af6930-ef04-474f-b975-1af28eb0c0e7     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 9249d114-e44e-4908-95d7-64f9e9e49b2f f2c89658-ecfa-47b9-a598-68a3453e0b7a     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f fa70ae0c-7108-48f8-943c-9fd41e22e271 0ba628a7-dc70-486b-be72-f2ed9bbe6c36     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 3b2daee6-e12f-450b-8afd-d5ca7a34bd6d 2a2f3d41-bde8-4800-baa1-f1a8a2a6bf9f     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 3abdae26-f731-4b05-8398-daf6f23d0e5a 9e80f5d9-bf47-402d-ad7c-d75eba55260d     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 8a1b1b70-f179-42fe-a03a-8d872a115f08 a868827d-b294-4715-8136-b8d611f2e1d4     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 777db328-c1dc-48be-8e0f-6b2553a467b3 1878e8b4-1d72-4b9c-b34b-0dd328e3ba89     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f f29def25-4e99-4915-b76f-0b9ccdd8ba6c 607ec92f-889d-4290-a35a-b354550a71e9     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 981b2af5-fefd-4449-b805-1dcac323628d 2da1d222-521b-4734-98df-7d52f6c7938b     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 5d3e4208-b67f-44fd-bbfa-b644b97f6bbd dbce6f7c-409f-4220-b1f9-ec1500a783f9     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 211dca0d-ba3e-44bd-8bfa-8680530347a3 707d28d0-c638-492d-b8c7-9c27eaa7e8fc     True          False                                                C:\
b40e4eb8-b98d-40d8-9176-8560146f907f 2a1da29c-e2b7-4ac6-9369-c3d15da8d17b be3557d4-0012-40a3-9f3a-704c2b89e769     True          False                                                C:\
 
```

**Comment by bk-cs** [comment]
The command example you provided shows a `ps` result which will not have the `batch_get_cmd_req_id` field. Only `get` command results will have that. Did you post the wrong example?

**Comment by datorr2** [comment]
No.  The `ps` command should have returned `$_.stdout`, shouldn't it?  It used to before.

Trying to perform a `ps` and get the results.

**Comment by bk-cs** [comment]
Nice catch! In v2.1.4 it looks like the `$_.stdout` field is not properly updating the result from the session initialization step (the value `C:\`) to the result of the command that's being used. This doesn't happen on v2.1.3. I'll look into this.

**Comment by bk-cs** [comment]
@datorr2 - this should be fixed with the commit I just made. Please replace your `Public\psfalcon.ps1` file with the latest (or re-download the source).

**Comment by datorr2** [comment]
@bk-cs Awesome, looks like it's working.  Thanks!

**Comment by thomass-mpg** [comment]
It appears that commands that are run with Invoke-FalconRTR, that do not return anything to stdout, return "C:\" instead of nothing (on a windows host). Is that intended behavior? (tested on psfalcon-master)
For example:

`Running: 
Invoke-FalconRTR -Command runscript -Arguments ('-Raw=``` nonexistent-command``` ') -HostIds $targetHostList

Windows response:
aid              : x
batch_id         : x
session_id       : x
cloud_request_id : x
complete         : True
offline_queued   : False
errors           :
stderr           : The term 'nonexisting-command' is not recognized as the name of a cmdlet, function, script file, or
                   operable program. Check the spelling of the name, or if a path was included, verify that the path
                   is correct and try again.
stdout           : C:\


Linux response:
aid              : x
batch_id         : x
session_id       : x
cloud_request_id : x
complete         : True
offline_queued   : False
errors           :
stderr           : /bin/bash: nonexisting-command: command not found
stdout           : /`

**Comment by bk-cs** [comment]
`Invoke-FalconRtr` is a combination of commands:

1. `Start-FalconSession`, using the `-HostIds` parameter to initiate a batch session
2. `Invoke-FalconCommand`, `Invoke-FalconResponderCommand`, or `Invoke-FalconAdminCommand`, depending on the command issued

Whenever `Start-FalconSession` is successful, a `stdout` value of the root drive is returned. As `Invoke-FalconRtr` goes through the steps, it records the output of the session creation, then overwrites it with the output of the command.

So, with how it works right now, it's expected to see the `C:\` or `/` value, as `Invoke-FalconRtr` updates the `stdout` and `stderr` fields when there is content. I get the impression that this will likely be confusing for most users, so I can update it to not include the `stdout` result from `Start-FalconSession`. Do you think that's a better result?

**Comment by thomass-mpg** [comment]
Ah, that explains it!
I do think that it would be better to hide the root drive in this scenario. I was running some scripts and commands that shouldn't have been returning anything to `stdout`, and was going crazy trying to figure out why they were returning the root drive!
Thank you.

**Comment by bk-cs** [comment]
The [v2.1.4 release](https://github.com/CrowdStrike/psfalcon/releases/tag/2.1.4) is available on GitHub and will be published to the PowerShell Gallery soon. It includes the `stdout` change mentioned above.
